ecom_web/cart/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('cart_home', views.cart_home, name='cart_home'),
    path('update', views.cart_update, name='update')
]

ecom_web/ecom_web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('sell.urls','sell'),namespace='sell')),
    path('',include(('user.urls', 'user'),namespace='user')),
    path('',include(('cart.urls', 'cart'),namespace='cart')),
    path('',include(('payment.urls','payment'),namespace='payment')),
    url('oauth/', include('social_django.urls', namespace='social')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom_web/payment/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('checkout', views.checkout_page, name='checkout'),
    path('recipt', views.recipt, name='recipt'),
    path('handlerequest', views.handlerequest, name='handlerequest'),
]

ecom_web/sell/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.homepage, name='home'),
    path('new', views.newpage, name='new'),
    path('sell', views.sell, name='sell'),
    path('<slug:old_product_slug>/', views.detail, name='detail'), 
    path('new/<slug:product_slug>/', views.newdetail, name='newdetail'),
]

ecom_web/user/urls.py
from . import views
from django.urls import path,re_path,reverse_lazy
from django.contrib.auth import views as auth_views
from django.conf.urls import url,include
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('login', views.user_login, name='user_login'),
    path('logout', views.user_logout, name='user_logout'),
    path('register',views.register,name='register'),
    path('', include('django.contrib.auth.urls')),
    
    path('edit_profile',views.edit_profile,name='edit_profile'),
    
    # password reset url's
    path('password-change/done', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password-change', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('password-reset/confirm//<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('user:password_reset_complete')), name='password_reset_confirm'),
    
    path('password-reset', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
         email_template_name = 'registration/password_reset_email.html',
         success_url = reverse_lazy('user:password_reset_done')),name='password_reset'),
    
    path('password-reset/complete', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    

    

]

ecom_web/templates/NewPost.html
{% extends "base.html" %}
{% block content %}
<h1>This Is New Posts Page</h1>
<br>
<!-- POSTS -->
<div class="row">
	{% for item in post %}
				<div class="col-lg-3 col-md-6 mb-lg-0 mb-4">
					<!--Collection card-->
					<div class="card collection-card" style="width: 20rem;">
						<!--Card image-->
						<div class="view zoom">
							<img class="img-fluid" src="{{ item.image1.url }}"
								alt="Example photo"  width="400" style="max-height: 250;"> 
							<div class="stripe_dark">
								<a href={% url 'sell:newdetail' item.slug %}>
								<p> {{item.title}}<br>Rs-{{item.price}} <i class="fas fa-chevron-right"></i></p>
								</a>
							</div>
						</div>
						<!--/.Card image-->
					</div>
					<!--/.Collection card-->
				</div>
					{% empty %}
					<div class="container-fluid">
					<h3>No Posts Found having search name "{{request.GET.q}}"</h3>
					</div>
	{% endfor %}
</div>
<style>
	.stripe_dark {
  width: 400;
  position: absolute;
  bottom: 0px;
  background-color:black;
  opacity: 0.6;
}
.stripe_dark a p{
	font-weight: bold;
	text-align:start;
	font-size: large;
	font-family: 'Times New Roman';
	color: white;
}
</style>
{% endblock %}

ecom_web/templates/base.html
{% load static %}
<html>
<head>
<title></title>
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet">
  {% block extrahead %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/"><i class="india flag"></i>BoAn Furnitures</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/new">New Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/sell">Sell</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/cart_home">Cart</a>
            </li>
            <li>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success my-2 my-sm-0" type="Submit">Search</button>
            </form>
            </li>
        </ul>
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if request.user.profile.Photo %}
                <img src="{{ request.user.profile.Photo.url }}" alt="" class="navbar-img">
            {% else %}
                <img src="/media/Profiles/default-user-img.jpg" alt="" class="navbar-img">
            {% endif %}
                <span>Hi {{ request.user|capfirst}}</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'user:edit_profile' %}">My Profile</a>
            <a class="dropdown-item" href="{% url 'user:user_logout' %}">Logout</a>
            </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{% url 'user:user_login' %}" class="nav-link">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
    </nav>
    <div class="container-fluid">
        {% block content %}

        {% endblock%}
    </div>

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script>
{% block js %} {% endblock %}
</body>
</html>

ecom_web/templates/cart_home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block extrahead %}
<style>
    table {
      font-family: arial, sans-serif; 
      border-collapse: collapse;
      width: 100%;
    }
    th {
        background-color: rgba(7, 158, 245, 0.938);
    }
    td, th {
      text-align: center;
      padding: 15px;
    }
</style>
{%endblock extrahead %}


{% block content %}
<h1>Your shopping cart</h1>
{% if cart.products.exists %}
     <table class="cart" border="10">
        <thead>
            <tr>
                <th>#</th>
            <!--    <th>Image</th> -->
                <th>Product</th>
            <!--  <th>Quantity</th>  -->
                <th>Remove</th>
            <!--  <th>Unit price</th>  -->                  
                <th>Price</th>
            </tr>
        </thead>
       <tbody>
        {% for product in cart.products.all %}
        <tr>
            <td scope="row">{{ forloop.counter }}</td>
            <td>{{ product.title }}</td>
            <td>
                {% include 'update_cart.html' with product=product cart=cart in_cart=True%}
            </td>
            <td>{{ product.price }} Rs</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="3"></td>
            <td><b>Subtotal : </b> {{cart.subtotal}} Rs</td>
        </tr>
        <tr>
            <td colspan="3"></td>
            <td><b>Total : </b> {{cart.total}} Rs</td>
        </tr>
        </tbody>
    </table>
    {% else %}
    <p class='lead'>Cart is empty</p>
    {% endif %} 
    <p class="text-right" style="margin-top: 5px;">
        <a href="/new" class="btn btn-primary btn-lg" >Continue shopping</a>
        <a href="checkout" class="btn btn-success btn-lg" >Checkout</a>
    </p>  
{% endblock %}

ecom_web/templates/checkout.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Your Checkout page</h1>
<br>
<div class="container">
    <div class="col">
        <h2>Your order details</h2>
        {% if cart.products.exists %}
        <div id="items">
            <ul class="list-group">
              {% for product in cart.products.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  {{ product.title }}
                <span class="badge badge-primary badge-pill">{{ product.price }} Rs</span>
                </li>
                {% endfor %}
            </ul>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb mt-3">
                <li class="breadcrumb-item actice" aria-current="page">Your cart total is <b>Rs. <span>{{cart.total}}</span></b> Enter your details below & place your order. Thankyou!</li>
              </ol>
            </nav>
        </div>
        {% else %}
          <p class='lead'>Your Cart is Empty, Please Buy something for checkout.</p>
        {% endif %}
      </div>
    <br>
    <div class="col">
        <h2>Please provide your accurate Shipping details</h2>
        <form method="POST" action="checkout">
          {% csrf_token%}
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="inputname">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
              </div>
              <div class="form-group col-md-6">
                <label for="inputPhone">Phone Number</label>
                <input type="tel" class="form-control" name="phone"id="phone">
              </div>
            </div>
            <div class="form-group">
                <label for="inputEmail4">Email</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Email">
            </div>
            <div class="form-group">
              <label for="inputAddress">Address</label>
              <input type="text" class="form-control" name="address1" id="address1" placeholder="1234 Main St">
            </div>
            <div class="form-group">
              <label for="inputAddress2">Address line 2</label>
              <input type="text" class="form-control" name="address2" id="address2" placeholder="Apartment, studio, or floor">
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="inputCity">City</label>
                <input type="text" class="form-control" name="city" id="city">
              </div>
              <div class="form-group col-md-4">
                <label for="inputState">State</label>
                <input type="text" class="form-control" name="state" id="state" placeholder="State">
              </div>
              <div class="form-group col-md-2">
                <label for="inputZip">Zip</label>
                <input type="text" class="form-control" name="zip_code" id="zip_code">
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Place order</button>
          </form>
    </div>
</div>
{% endblock %}

ecom_web/templates/edit_profile.html
{% extends "base.html" %}
{% block content %}
<h1>Edit Profile<h1>
<form action="edit_profile" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
  {{ user_form.as_table }}
  {{ profile_form.as_table }}
  </table>
  <input type="submit" class="btn btn-outline-success" value="Save Changes">
</form>
{% endblock %}

ecom_web/templates/home.html
{% extends "base.html" %}
{% block content %}
<h1>THIS IS A HOMEPAGE</h1>

<!-- POSTS -->
<br>

<div class="row">
	{% for item in post %}
				<div class="col-lg-3 col-md-6 mb-lg-0 mb-4">
					<!--Collection card-->
					<div class="card collection-card" style="width: 20rem;">
						<!--Card image-->
						<div class="view zoom">
						<img class="img-fluid" src="{{ item.image1.url }}"
							alt="Example photo"  width="400" style="max-height: 250;"> 
						<div class="stripe_dark">
							<a href="{{ item.slug }}">
							<p>{{item.title}}<br>Rs-{{item.price}} <i class="fas fa-chevron-right"></i></p>
							</a>
						</div>
						</div>
						<!--/.Card image-->
					</div>
					<!--/.Collection card-->
				</div>
					{% empty %}
					<div class="container-fluid">
					<h3>No Posts Found having search name "{{request.GET.q}}"</h3>
					</div>
	{% endfor %}
</div>
<style>
	.stripe_dark {
  width: 400;
  position: absolute;
  bottom: 0px;
  background-color:black;
  opacity: 0.6;
}
.stripe_dark a p{
	font-weight: bold;
	text-align:start;
	font-size: large;
	font-family: 'Times New Roman';
	color: white;
}
</style>
{% endblock %}

ecom_web/templates/login.html
{% extends "base.html" %}
{% block content %}
<h1>Enter username and password for login<h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <small>
    <a href="{% url 'user:register' %}">Register</a> | 
    <a href="{% url 'user:password_reset' %}">Forgotten your Password?</a>
  </small>
  <input type="submit" class="btn btn-outline-success" value="Login">
</form>
<br>
  <p><strong>-- OR --</strong></p>
  <a href="{% url 'social:begin' 'google-oauth2' %}">
    <button type="button" name="button"class="btn btn-danger">Login with google+</button>
  </a>
  <a href="{% url 'social:begin' 'twitter' %}">
    <button type="button" name="button"class="btn btn-info">Login with Twitter</button>
  </a>
  <a href="{% url 'social:begin' 'facebook' %}">
    <button type="button" name="button"class="btn btn-primary" onclick="">Login with Facebook</button>
  </a>

{% endblock %}

ecom_web/templates/oldpost_detail.html
{% extends "base.html" %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/detail_page.css' %}">
{% endblock %}

{% block content %}
<h1 class="text-primary">This is A Detailed page of {{post.title}}</h1>
<br>

<div class="w3-content w3-display-container">
  <img class="mySlides" src="{{ post.image1.url }}" style="width:50%;height:100%;margin-left: auto;margin-right: auto;" alt="Image 1">
  <img class="mySlides" src="{{ post.image2.url }}" style="width:50%;height:100%;margin-left: auto;margin-right: auto;" alt="Image 2">
  <img class="mySlides" src="{{ post.image3.url }}" style="width:50%;height:100%;margin-left: auto;margin-right: auto;" alt="Image 3">
  <img class="mySlides" src="{{ post.image4.url }}" style="width:50%;height:100%;margin-left: auto;margin-right: auto;" alt="Image 4">
  <img class="mySlides" src="{{ post.image5.url }}" style="width:50%;height:100%;margin-left: auto;margin-right: auto;" alt="Image 5">

  <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
  <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
</div>

<!-- The grid: five columns -->
<div class="row">
  <div class="column">
    <img src="{{ post.image1.url }}" style="width:100%;cursor:pointer" alt="Image 1" onclick="currentDiv(1)">
  </div>
  <div class="column">
    <img src="{{ post.image2.url }}" style="width:100%;cursor:pointer" alt="Image 2" onclick="currentDiv(2)">
  </div>
  <div class="column">
    <img src="{{ post.image3.url }}" style="width:100%;cursor:pointer" alt="Image 3" onclick="currentDiv(3)">
  </div>
  <div class="column">
    <img src="{{ post.image4.url }}" style="width:100%;cursor:pointer" alt="Image 4" onclick="currentDiv(4)">
  </div>
  <div class="column">
    <img src="{{ post.image5.url }}" style="width:100%;cursor:pointer" alt="Image 5" onclick="currentDiv(5)">
  </div>
</div>

<div> 
<h1 class="text-primary">For Rs - {{post.price}} </h1>
<br> 
<dl><h3 class="text-primary"><dt>Description </dt><small><dd> - {{post.description}} </dd></small></h3>
</dl>
</div> 
<script>
var slideIndex = 1;
showDivs(slideIndex);

function currentDiv(n) {
  showDivs(slideIndex = n);
}

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
  }
  x[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " w3-opacity-off";
}
</script>
{% endblock %}

ecom_web/templates/paymentstatus.html
{% load static %}
<html>
    <head>
        <title>Payment status page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    
        <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
<body>
<!-- <div class="container">
    <br>
    {{response}}
    <br>
    <br>
    <h2>Callback Messsage: </h2>                    <br>
    <h3> Checksum Verification: {{ response.message }} </h3> <br>
    MID: {{ response.MID }}                                  <br>
    TXNID: {{ response.TXNID }}                              <br>
    ORDERID: {{ response.ORDERID }}                          <br>
    BANKTXNID: {{ response.BANKTXNID }}                      <br>
    TXNAMOUNT: {{ response.TXNAMOUNT }}                      <br>
    CURRENCY: {{ response.CURRENCY }}                        <br>
    <h3> STATUS: {{ response.STATUS }} </h3>                 <br>
    RESPCODE: {{ response.RESPCODE }}                        <br>
    RESPMSG: {{ response.RESPMSG }}                          <br>
    TXNDATE: {{ response.TXNDATE }}                          <br>
    GATEWAYNAME: {{ response.GATEWAYNAME }}                  <br>
    BANKNAME: {{ response.BANKNAME }}                        <br>                
    PAYMENTMODE: {{ response.PAYMENTMODE }}                  <br>
    CHECKSUMHASH: {{ response.CHECKSUMHASH }}
    <div class="col my-4">

        <h2>Payment status regarding your order Id : {{response.ORDERID}}</h2>
        {% if response.RESPCODE == '01' %}
        ORDER SUCCESS
        {% else %}
        ORDER FAILURE
        {% endif%}
        <a href="/new" class="btn btn-primary btn-lg" >Continue shopping</a>
    </div>
    <br>
    {% for key,value in response.items %}
        {{key}} =  {{value}} <br>
    {% endfor %}
</div>-->
<div class="container">
    <div class="row justify-content-center">
      <div class="col-11 col-md-7 mt-5 mb-5 border-primary pricing">
        <p class="text-primary">BoAn Furnitures Payments!!!</p>
        <p class="text-primary">Please Do Not Refresh The Page.</p>
        <p class="text-primary">Transaction processing</p>
        <form method="POST" action="{% url 'payment:recipt' %}"  name="save_details" enctype="multipart/form-data">
        <table border="1">
        <tbody>
        {% for key,value in response.items %}
          {% if key == 'MID' or key == 'PAYMENTMODE' or key == 'CURRENCY' or key == 'RESPCODE' or key == 'GATEWAYNAME' or key == 'BANKNAME' %}
            <input type="hidden" name="{{key}}" value="{{value}}">
          {% elif key == 'TXNDATE' %}
            <input type="hidden" type="datetime" name="{{key}}" value="{{value}}">
          {% else %}
            <input type="hidden" class="form-control" type="text" name="{{key}}" value="{{value}}" readonly="readonly">
          {% endif %}
        {% endfor %}
        <!-- <h2>{{ user }}</h2> -->
        </tbody>
        </table>
        <script type="text/javascript">
          document.save_details.submit();
        </script>
        <!-- <button class="btn btn-primary px-4 py-2" type="submit"> Submit Transaction Details</button> -->
        </form>
      </div>
    </div>
  </div>
</body> 

</html>

ecom_web/templates/paytm.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>Paytm merchant payment page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

        <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'css/aos.css' %}">

        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-11 col-md-8 mt-5 mb-5 border-primary pricing">
                  <p class="text-primary">BoAn Furntures Payments!!!</p>
                  <p class="text-primary">Merchant Check Out Page.</p>
                  <p class="text-primary">Please Do Not Refresh The Page.</p>
                  <p class="text-primary">You are getting Redirected to the Payment Gateway.</p>
                  <form action="https://securegw-stage.paytm.in/theia/processTransaction" method="post" name="paytm">
                       {% for key, value in param_dict.items %}
                       <input type="hidden" name="{{key}}" value="{{value}}">
                       {% endfor %}
                       <!-- <h2>{{ user }}</h2> -->
                       <script>
                        document.paytm.submit()
                        </script>
                  </form>
                </div>
            </div>
          </div>
    </body>
</html>

ecom_web/templates/register.html
{% extends "base.html" %}
{% block content %}
<h1>Registration Form :-<h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-outline-success" value="Register">
</form>
{% endblock %}

ecom_web/templates/sellpage.html
{% extends "base.html" %}
{% block content %}
<h1>POST YOUR AD<h1>
<form method="POST" action="/sell" enctype="multipart/form-data" >
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" class="btn btn-primary btn-lg" value="Post">
</form>
{% endblock %}

ecom_web/templates/update_cart.html
<form method="POST" action="{% url 'cart:update' %}" class="form">
    {% csrf_token %}
    <input type="hidden" name="product_id" value='{{product.id}}'>
    
    {% if in_cart %}
        <button type='submit' class="btn btn-danger">Remove</button>
    {% else %}
        {% if post in cart.products.all %}
        Already in Cart :  <button type='submit' class="btn btn-danger">Remove from Cart</button>
        {% else %}
        <button type='submit' class="btn btn-success">Add to Cart</button>
        {% endif %}
    {% endif %}    
  </form>